spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: liyuelin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 15
      max-lifetime: 540000
      minimum-idle: 10
      idle-timeout: 500000
      pool-name: HikariPool
      connection-timeout: 60000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql